#!/bin/bash
env PYTHONPATH=. env/bin/python -m ipfixd_app.main $* << EOF
import ipfixd_app.main
import cProfile

try:
    exit( cProfile.run( 'ipfixd_app.main.main()' ) )
except KeyboardInterrupt:
    pass
EOF
